# fluentd/Dockerfile
FROM fluent/fluentd:latest
RUN ["gem", "install", "fluent-plugin-elasticsearch"]
 #, "--no-rdoc", "--no-ri", "--version", "1.9.2"]
#RUN ["gem", "install", "elasticsearch", "--version", "7.4.0"]
