version: '3.5'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      default:
        ipv4_address: 172.18.0.2
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      default:
        ipv4_address: 172.18.0.3
    environment:
      discovery.type: single-node
  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      default:
        ipv4_address: 172.18.0.4
networks:
  default:
    external:
      name: appnet
